from .split_into_sentences import split_into_sentences_test
from .remove_punctuation import remove_punctuation_test
from .lower import lower_test
from .split_into_words import split_into_words_test
from .create_bag_of_words import create_bag_of_words_test
from .create_training_data_in_words_for_sentence import create_training_data_in_words_for_sentence_test as create_training_data_in_words_for_sentence_test
from .create_training_data_in_words import create_training_data_in_words_test
from .create_init_word_to_idx_count_vocab import create_init_word_to_idx_count_vocab_test
from .add_window_count_to_word_to_idx_count_vocab_via_words import add_window_count_to_word_to_idx_count_vocab_via_words_test
from .reduce_word_to_idx_count_vocab_via_window_count import reduce_word_to_idx_count_vocab_via_window_count_test
from .reduce_context_window_and_map_to_idx import reduce_context_window_and_map_to_idx_test
from .reduce_training_data_and_map_to_idx import reduce_training_data_and_map_to_idx_test


split_into_sentences_test.runTest()
remove_punctuation_test.runTest()
lower_test.runTest()
split_into_words_test.runTest()
create_bag_of_words_test.runTest()
create_training_data_in_words_for_sentence_test.runTest()
create_training_data_in_words_test.runTest()
create_init_word_to_idx_count_vocab_test.runTest()
add_window_count_to_word_to_idx_count_vocab_via_words_test.runTest()
reduce_word_to_idx_count_vocab_via_window_count_test.runTest()
reduce_context_window_and_map_to_idx_test.runTest()
reduce_training_data_and_map_to_idx_test.runTest()
